services:
  backend:
    image: sarathi_backend
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: sarathi_backend

    ports:
      - "8000:8000"

    env_file:
      - ./backend/.env

    volumes:
      - ./backend:/backend
      - /backend/node_modules

    command: npm run dev

    restart: unless-stopped

    networks:
      - sarathi_store_net

  frontend:
    image: sarathi_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: sarathi_frontend

    ports:
      - "3000:3000"

    depends_on:
      - backend

    restart: unless-stopped

    networks:
      - sarathi_store_net

networks:
  sarathi_store_net:
    driver: bridge