services:
  backend:
    image: prathazon_backend
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: prathazon_backend

    ports:
      - "8000:8000"

    env_file:
      - ./backend/.env

    volumes:
      - ./backend:/backend
      - /backend/node_modules

    command: npm run dev

    restart: unless-stopped

    networks:
      - prathazon_net

  frontend:
    image: prathazon_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: prathazon_frontend

    ports:
      - "3000:3000"

    depends_on:
      - backend

    restart: unless-stopped

    networks:
      - prathazon_net

networks:
  prathazon_net:
    driver: bridge